### ISSUE TITLE
A collision for Host ID 'mmaremovalutility-extensionremov' was detected in the configured storage account

### ISSUE THREAD

**Issue by giraudeo** [azsk/AzTS-docs#473]
Hello,

We are into the removing phase, but start getting an issue to trigger the removal.
What we see, is a Red message in the Azure portal when we go to the function apps "MMARemovalUtility-ExtensionRemoval-xxxx" and "MMARemovalUtility-ExtensionRemovalStatusCheck-xxxx":
A collision for Host ID 'mmaremovalutility-extensionremov' was detected in the configured storage account. For more information, see https://aka.ms/functions-hostid-collision.

As you can see, those 2 functions will have same name because of a 32 char limit if I understood correctly.

I think it has the side effect the removal is not triggered (so far, it does not want to start at least).

What do you advise to fix it?

Regards,

**Comment by MJaithra** [comment]
Hello,

We wanted to inform you that the MMA Removal Utility is currently on a deprecation path and is no longer actively supported or being worked upon. We have received similar reports from other end users indicating that the tool is encountering errors, where the MMA agents are not being removed successfully.
 
At this time, we advise against using this utility due to its current state and lack of active support. We apologize for any inconvenience this may cause and recommend considering alternative methods for managing MMA agent removal.
 
Thank you for your understanding.

**Comment by giraudeo** [comment]
Hello MJaithra,

I do understand the tool was removed from the official Microsoft documentation, but it was still presented as a solution to remove the old extension until June 2024 (2 months before legacy agents (OMS/MMA) are deprecated.

To drop the support, even for certainly not too complex issues, is a little "harsh".

As a company, we cannot just drop all the effort and time we put to deploy this solution.
The "new" alternative to use a script to run on a per subscription basis is in fact not so convenient in comparaison.

Is there a way to at least still help for easy-to-fix problems?

In this case, we already deployed a solution by making the Function app names shorter.
Optimal solution would be to define a xxx__hostid parameter to be unique per Function.

If the support is limited, any possibility to open the code source of the Function app packages?

Regards,

**Comment by JeffreyWolford** [comment]
The tool is just too difficult to use for customers and to maintain for the product group.  It is not a formal product that is covered by our normal deprecation processes. We will not be maintaining it.  

Please use the new version of the script.
