### ISSUE TITLE
PreReq checks are wrong

### ISSUE THREAD

**Issue by fume** [azsk/AzTS-docs#476]
AzureAD module is installed instead of Az.ResourceGraph module.
https://github.com/azsk/AzTS-docs/blob/97e9ffb53537e7de9a1fee1a8be3738ef25a8a67/Scripts/RemediationScripts/Remediate-InvalidAADObjectRoleAssignments.ps1#L83-L87

Moreover, the check for the AzureAD module doesn't check if one has the AzureADPreview module. If one has AzureADPreview module installed, the install-package cmd will fail.
https://github.com/azsk/AzTS-docs/blob/97e9ffb53537e7de9a1fee1a8be3738ef25a8a67/Scripts/RemediationScripts/Remediate-InvalidAADObjectRoleAssignments.ps1#L94-L98

**Comment by TarunKrShukla** [comment]
Hi @fume,

Thanks for bringing this to our notice. We have fixed the issue where AzureAD module was getting installed instead of Az.ResourceGraph module. We are not adding support for both AzureAD and AzureADPreview because some of the commands which are there in AzureAD module but are not available in AzureADPreview. 
Thanks once again for your contribution.

Thanks!
